import type { BrewTemplate } from './brewTemplateTypes'

function step(
  order: number,
  startSeconds: number,
  endSeconds: number | null,
  targetWaterGrams: number,
  label: string,
  action: string,
) {
  return { order, startSeconds, endSeconds, targetWaterGrams, label, action }
}

export const brewTemplates: BrewTemplate[] = [
  {
    id: 'classic-v60-three-pour',
    name: '经典三段式 V60',
    category: 'daily-pourover',
    difficulty: 'easy',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 240,
    ratio: '1:16',
    waterTemperatureC: { min: 91, max: 93 },
    grindSize: '中细',
    targetTimeSeconds: { min: 140, max: 170 },
    pourSteps: [
      step(1, 0, 30, 40, '闷蒸', '中心向外注水到 40g，轻晃滤杯让粉层湿润。'),
      step(2, 30, 70, 140, '主注水', '稳定绕圈注水到 140g，保持水位不过高。'),
      step(3, 70, 130, 240, '收尾', '继续注水到 240g，等待自然滴滤完成。'),
    ],
    suitableFor: ['水洗', '浅烘', '中浅烘', '明亮', '柑橘', '日常'],
    avoidFor: ['深烘', '发酵感很强'],
    flavorGoal: '干净、均衡、容易复现。',
    adjustmentRules: [
      '酸尖时降低 1-2°C 或研磨略粗。',
      '味道空时研磨略细或把总时间拉长 10-15 秒。',
    ],
    sourceNotes: '日常 V60 三段式基础模板，用于新豆试冲和稳定记录。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'v60-five-pulse',
    name: 'V60 五段脉冲注水',
    category: 'daily-pourover',
    difficulty: 'medium',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 250,
    ratio: '1:16.7',
    waterTemperatureC: { min: 92, max: 94 },
    grindSize: '中细到中等',
    targetTimeSeconds: { min: 150, max: 190 },
    pourSteps: [
      step(1, 0, 30, 50, '闷蒸', '注水到 50g，确认粉层充分湿润。'),
      step(2, 30, 60, 100, '第一段', '轻柔绕圈注水到 100g。'),
      step(3, 60, 90, 150, '第二段', '注水到 150g，维持稳定水流。'),
      step(4, 90, 120, 200, '第三段', '注水到 200g，避免冲到滤纸边缘。'),
      step(5, 120, 150, 250, '收尾', '注水到 250g，等待滴滤完成。'),
    ],
    suitableFor: ['浅烘', '中浅烘', '甜感', '均衡', '莓果'],
    avoidFor: ['极细粉多', '易堵塞'],
    flavorGoal: '提高甜感和萃取均匀度。',
    adjustmentRules: [
      '流速太慢时减少分段或研磨略粗。',
      '甜感不足时延长中段间隔 5-10 秒。',
    ],
    sourceNotes: '多段脉冲注水模板，适合想更细致控制萃取的手冲。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'v60-single-main-pour',
    name: 'V60 单次主注水',
    category: 'daily-pourover',
    difficulty: 'medium',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 16,
    waterGrams: 256,
    ratio: '1:16',
    waterTemperatureC: { min: 92, max: 95 },
    grindSize: '中细',
    targetTimeSeconds: { min: 135, max: 170 },
    pourSteps: [
      step(1, 0, 45, 48, '闷蒸', '注水到 48g，轻轻旋转让粉床均匀湿润。'),
      step(2, 45, 105, 256, '单次主注水', '连续稳定注水到 256g，减少中途停顿。'),
      step(3, 105, null, 256, '滴滤', '轻晃一次，让粉床保持平整后等待完成。'),
    ],
    suitableFor: ['水洗', '明亮', '花香', '干净', '浅烘'],
    avoidFor: ['日晒厚甜', '需要高浓度'],
    flavorGoal: '减少扰动，突出清晰度。',
    adjustmentRules: [
      '风味薄时研磨略细。',
      '尾段苦涩时减少晃动或降低水温。',
    ],
    sourceNotes: '受单次主注水思路启发，适合清晰型水洗豆。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'hoffmann-v60-inspired',
    name: 'Hoffmann 风格 V60',
    category: 'daily-pourover',
    difficulty: 'medium',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 18,
    waterGrams: 300,
    ratio: '1:16.7',
    waterTemperatureC: { min: 93, max: 96 },
    grindSize: '中细',
    targetTimeSeconds: { min: 180, max: 220 },
    pourSteps: [
      step(1, 0, 45, 45, '充分闷蒸', '注水到 45g，旋转滤杯确保无干粉。'),
      step(2, 45, 75, 180, '快速注水', '较快注水到 180g，建立足够水位。'),
      step(3, 75, 105, 300, '补足水量', '继续注水到 300g，结束后轻轻旋转。'),
      step(4, 105, null, 300, '平整粉床', '等待滴滤完成，目标粉床平整。'),
    ],
    suitableFor: ['浅烘', '中浅烘', '高萃取', '花香', '柑橘'],
    avoidFor: ['深烘', '厌氧刺激感强'],
    flavorGoal: '高萃取、均匀、完整。',
    adjustmentRules: [
      '苦涩时降低水温或研磨略粗。',
      '酸弱且空时提高水温或研磨略细。',
    ],
    sourceNotes: '参考 James Hoffmann V60 技法的均匀浸润和旋转思路。',
    sourceUrls: ['https://www.seriouseats.com/perfect-coffee-bubbles-signs-sounds-6824133'],
    isChampionReference: false,
  },
  {
    id: 'kasuya-46-daily',
    name: '4:6 日常甜感模板',
    category: 'daily-pourover',
    difficulty: 'medium',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 20,
    waterGrams: 300,
    ratio: '1:15',
    waterTemperatureC: { min: 90, max: 93 },
    grindSize: '中粗',
    targetTimeSeconds: { min: 210, max: 240 },
    pourSteps: [
      step(1, 0, 45, 60, '甜酸控制 1', '注水到 60g，等待水位下降。'),
      step(2, 45, 90, 120, '甜酸控制 2', '注水到 120g，建立前段风味。'),
      step(3, 90, 135, 180, '浓度控制 1', '注水到 180g。'),
      step(4, 135, 180, 240, '浓度控制 2', '注水到 240g。'),
      step(5, 180, 225, 300, '浓度控制 3', '注水到 300g，等待滴滤。'),
    ],
    suitableFor: ['日晒', '蜜处理', '甜感', '莓果', '层次'],
    avoidFor: ['极浅烘高密度且难萃取'],
    flavorGoal: '拉开层次，增强甜感。',
    adjustmentRules: [
      '想更甜时提高第一段水量、降低第二段水量。',
      '想更高浓度时把后 60% 拆成更多段。',
    ],
    sourceNotes: '参考 Tetsu Kasuya 4:6 方法，用日常参数表达。',
    sourceUrls: ['https://en.wikipedia.org/wiki/World_Brewers_Cup'],
    isChampionReference: false,
  },
  {
    id: 'april-flat-low-agitation',
    name: '平底低扰动甜感模板',
    category: 'daily-pourover',
    difficulty: 'easy',
    brewer: '平底滤杯',
    filter: '平底滤纸',
    doseGrams: 13,
    waterGrams: 200,
    ratio: '1:15.4',
    waterTemperatureC: { min: 90, max: 94 },
    grindSize: '中等',
    targetTimeSeconds: { min: 150, max: 190 },
    pourSteps: [
      step(1, 0, 30, 50, '第一段', '中心小圈注水到 50g。'),
      step(2, 30, 60, 100, '第二段', '注水到 100g，水流保持低扰动。'),
      step(3, 60, 90, 150, '第三段', '注水到 150g。'),
      step(4, 90, 120, 200, '收尾', '注水到 200g，等待完成。'),
    ],
    suitableFor: ['甜感', '日晒', '平底', '莓果', '中浅烘'],
    avoidFor: ['需要强烈明亮酸质'],
    flavorGoal: '甜、圆润、低扰动。',
    adjustmentRules: [
      '味道闷时研磨略粗或减少总时间。',
      '酸尖时降低水温 1°C。',
    ],
    sourceNotes: '平底滤杯少量多段低扰动思路。',
    sourceUrls: ['https://www.foodandwine.com/pour-over-coffee-guide-11683863'],
    isChampionReference: false,
  },
  {
    id: 'kalita-wave-stable-sweet',
    name: 'Kalita Wave 平底稳定甜感',
    category: 'daily-pourover',
    difficulty: 'easy',
    brewer: 'Kalita Wave 平底滤杯',
    filter: 'Wave 平底滤纸',
    doseGrams: 18,
    waterGrams: 300,
    ratio: '1:16.7',
    waterTemperatureC: { min: 91, max: 94 },
    grindSize: '中等到中粗',
    targetTimeSeconds: { min: 210, max: 240 },
    pourSteps: [
      step(1, 0, 45, 45, '闷蒸', '注水到 45g，等待 30-45 秒。'),
      step(2, 45, 80, 120, '脉冲 1', '分次小水流注水到 120g。'),
      step(3, 80, 125, 210, '脉冲 2', '维持粉床上方水位，注水到 210g。'),
      step(4, 125, 170, 300, '脉冲 3', '注水到 300g，等待滴滤完成。'),
    ],
    suitableFor: ['甜感', '坚果', '巧克力', '平衡', '中烘'],
    avoidFor: ['追求极高香气穿透力'],
    flavorGoal: '稳定、甜感、厚实。',
    adjustmentRules: [
      '滴滤慢时研磨略粗。',
      '甜感不足时延长闷蒸或提高水温。',
    ],
    sourceNotes: '参考 Kalita Wave 平底滤杯通过平底结构维持稳定水位和甜感。',
    sourceUrls: [
      'https://www.seriouseats.com/how-to-brew-coffee-using-a-kalita-wave-dripper-pourover-japanese-technique',
    ],
    isChampionReference: false,
  },
  {
    id: 'origami-cone-bright',
    name: 'Origami 锥形明亮模板',
    category: 'daily-pourover',
    difficulty: 'medium',
    brewer: 'Origami',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 240,
    ratio: '1:16',
    waterTemperatureC: { min: 92, max: 95 },
    grindSize: '中细',
    targetTimeSeconds: { min: 125, max: 160 },
    pourSteps: [
      step(1, 0, 35, 40, '闷蒸', '注水到 40g，轻晃滤杯。'),
      step(2, 35, 75, 140, '主注水', '注水到 140g，水流略集中。'),
      step(3, 75, 115, 240, '收尾', '注水到 240g，保持快流速。'),
    ],
    suitableFor: ['水洗', '瑰夏', '花香', '柑橘', '明亮'],
    avoidFor: ['深烘', '需要厚重口感'],
    flavorGoal: '明亮、茶感、香气清楚。',
    adjustmentRules: [
      '流速过快导致空时研磨略细。',
      '香气闷时减少扰动。',
    ],
    sourceNotes: 'Origami 锥形滤纸通常流速较快，适合清晰明亮表达。',
    sourceUrls: ['https://www.seriouseats.com/origami-dripper-review-8731737'],
    isChampionReference: false,
  },
  {
    id: 'origami-flat-sweet',
    name: 'Origami 平底厚甜模板',
    category: 'daily-pourover',
    difficulty: 'medium',
    brewer: 'Origami',
    filter: '平底滤纸',
    doseGrams: 16,
    waterGrams: 250,
    ratio: '1:15.6',
    waterTemperatureC: { min: 90, max: 93 },
    grindSize: '中等',
    targetTimeSeconds: { min: 170, max: 210 },
    pourSteps: [
      step(1, 0, 40, 50, '闷蒸', '注水到 50g，等待粉层排气。'),
      step(2, 40, 80, 125, '甜感段', '低水流注水到 125g。'),
      step(3, 80, 125, 200, '浓度段', '注水到 200g，维持平整粉床。'),
      step(4, 125, 160, 250, '收尾', '注水到 250g。'),
    ],
    suitableFor: ['日晒', '蜜处理', '甜感', '莓果', '厚实'],
    avoidFor: ['非常易堵塞的细粉'],
    flavorGoal: '提高甜感和圆润度。',
    adjustmentRules: [
      '闷涩时研磨略粗。',
      '酸质不足时提高水温 1°C。',
    ],
    sourceNotes: 'Origami 使用平底滤纸时接触时间更长，杯感更厚。',
    sourceUrls: ['https://www.seriouseats.com/origami-dripper-review-8731737'],
    isChampionReference: false,
  },
  {
    id: 'orea-fast-flat',
    name: 'Orea 快流速平底模板',
    category: 'daily-pourover',
    difficulty: 'medium',
    brewer: 'Orea',
    filter: '平底滤纸',
    doseGrams: 15,
    waterGrams: 250,
    ratio: '1:16.7',
    waterTemperatureC: { min: 92, max: 95 },
    grindSize: '中细',
    targetTimeSeconds: { min: 120, max: 160 },
    pourSteps: [
      step(1, 0, 35, 45, '闷蒸', '注水到 45g，确保无干粉。'),
      step(2, 35, 70, 150, '快速主注水', '注水到 150g，利用快流速提高萃取。'),
      step(3, 70, 105, 250, '收尾', '注水到 250g，等待完成。'),
    ],
    suitableFor: ['浅烘', '高密度', '干净', '花香', '明亮'],
    avoidFor: ['深烘', '低密度易萃取'],
    flavorGoal: '快流速下取得清晰高萃取。',
    adjustmentRules: [
      '味道薄时研磨略细。',
      '涩感上升时减少最后一段扰动。',
    ],
    sourceNotes: '快流速平底滤杯模板，适合高萃取但避免堵塞。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'switch-immersion-release',
    name: 'Switch 浸泡滤杯释放法',
    category: 'immersion-hybrid',
    difficulty: 'easy',
    brewer: 'Switch 浸泡滤杯',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 240,
    ratio: '1:16',
    waterTemperatureC: { min: 90, max: 94 },
    grindSize: '中等',
    targetTimeSeconds: { min: 180, max: 230 },
    pourSteps: [
      step(1, 0, 20, 240, '关闭阀门注水', '关闭阀门，一次性注水到 240g，轻轻搅拌。'),
      step(2, 20, 150, 240, '浸泡', '盖上或静置，等待浸泡萃取。'),
      step(3, 150, null, 240, '释放', '打开阀门，让咖啡液过滤完成。'),
    ],
    suitableFor: ['新手', '稳定', '厚实', '甜感', '办公室'],
    avoidFor: ['追求极致明亮'],
    flavorGoal: '降低手法影响，得到厚实且干净的杯感。',
    adjustmentRules: [
      '苦涩时缩短浸泡或降低水温。',
      '味道淡时延长浸泡 20-30 秒。',
    ],
    sourceNotes: 'Switch 浸泡滤杯通过浸泡释放降低注水难度。',
    sourceUrls: ['https://www.seriouseats.com/hario-switch-review-11865428'],
    isChampionReference: false,
  },
  {
    id: 'switch-hybrid-bright-sweet',
    name: 'Switch 浸泡滤杯前浸泡后过滤',
    category: 'immersion-hybrid',
    difficulty: 'medium',
    brewer: 'Switch 浸泡滤杯',
    filter: '锥形滤纸',
    doseGrams: 16,
    waterGrams: 250,
    ratio: '1:15.6',
    waterTemperatureC: { min: 91, max: 94 },
    grindSize: '中等',
    targetTimeSeconds: { min: 170, max: 220 },
    pourSteps: [
      step(1, 0, 40, 80, '关闭阀门浸泡', '关闭阀门，注水到 80g，轻搅拌。'),
      step(2, 40, 75, 80, '释放前段', '打开阀门，让前段液体开始通过。'),
      step(3, 75, 120, 180, '过滤注水', '打开状态下注水到 180g。'),
      step(4, 120, 160, 250, '收尾', '注水到 250g，等待完成。'),
    ],
    suitableFor: ['甜感', '明亮', '浅烘', '中浅烘'],
    avoidFor: ['深烘苦感明显'],
    flavorGoal: '前段厚甜，后段保持清晰。',
    adjustmentRules: [
      '厚度不足时延长关闭阀门时间。',
      '干涩时降低水温或研磨略粗。',
    ],
    sourceNotes: 'Switch 混合式模板，利用阀门切换控制接触时间。',
    sourceUrls: ['https://www.seriouseats.com/hario-switch-review-11865428'],
    isChampionReference: false,
  },
  {
    id: 'clever-stable-immersion',
    name: '聪明杯稳定浸泡',
    category: 'immersion-hybrid',
    difficulty: 'easy',
    brewer: '聪明杯',
    filter: '#4 滤纸',
    doseGrams: 22,
    waterGrams: 330,
    ratio: '1:15',
    waterTemperatureC: { min: 91, max: 94 },
    grindSize: '中粗',
    targetTimeSeconds: { min: 210, max: 260 },
    pourSteps: [
      step(1, 0, 30, 70, '预浸泡', '注水到 70g，轻轻搅拌后盖上。'),
      step(2, 30, 45, 330, '补足水量', '注水到 330g，再轻搅一圈。'),
      step(3, 45, 210, 330, '浸泡', '静置浸泡。'),
      step(4, 210, null, 330, '释放', '放到杯上释放，过滤完成后移开。'),
    ],
    suitableFor: ['稳定', '厚实', '甜感', '办公室', '新手'],
    avoidFor: ['追求极轻盈茶感'],
    flavorGoal: '稳定、饱满、低失误率。',
    adjustmentRules: [
      '萃取过强时缩短浸泡或研磨略粗。',
      '风味淡时延长浸泡 30 秒。',
    ],
    sourceNotes: '参考聪明杯浸泡后释放流程。',
    sourceUrls: [
      'https://www.seriouseats.com/how-to-brew-coffee-in-a-clever-dripper-coffee-technique-tips',
    ],
    isChampionReference: false,
  },
  {
    id: 'clean-french-press',
    name: '法压壶清澈版',
    category: 'immersion-hybrid',
    difficulty: 'easy',
    brewer: '法压壶',
    filter: '金属滤网',
    doseGrams: 30,
    waterGrams: 450,
    ratio: '1:15',
    waterTemperatureC: { min: 90, max: 94 },
    grindSize: '中粗',
    targetTimeSeconds: { min: 540, max: 600 },
    pourSteps: [
      step(1, 0, 30, 450, '注水', '一次性注水到 450g，确保粉水混合。'),
      step(2, 30, 240, 450, '浸泡', '静置 4 分钟。'),
      step(3, 240, 300, 450, '破壳撇沫', '轻轻搅拌表层并撇去浮沫。'),
      step(4, 300, 540, 450, '沉降', '继续静置，让细粉沉降。'),
      step(5, 540, null, 450, '轻压倒出', '滤网只压到液面附近，慢慢倒出。'),
    ],
    suitableFor: ['中烘', '坚果', '巧克力', '多人分享', '厚实'],
    avoidFor: ['极高花香型豆子'],
    flavorGoal: '保留法压厚度，同时降低浑浊和细粉感。',
    adjustmentRules: [
      '苦味重时降低水温或缩短初段浸泡。',
      '口感太薄时提高粉水比到 1:14。',
    ],
    sourceNotes: '参考现代清澈法压思路，延长沉降并避免用力下压。',
    sourceUrls: ['https://www.epicurious.com/expert-advice/how-to-use-a-french-press-to-make-coffee'],
    isChampionReference: false,
  },
  {
    id: 'washed-light-bright',
    name: '水洗浅烘明亮模板',
    category: 'bean-specific',
    difficulty: 'easy',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 245,
    ratio: '1:16.3',
    waterTemperatureC: { min: 93, max: 95 },
    grindSize: '中细',
    targetTimeSeconds: { min: 145, max: 180 },
    pourSteps: [
      step(1, 0, 40, 45, '闷蒸', '注水到 45g，充分排气。'),
      step(2, 40, 85, 150, '清晰段', '注水到 150g，保持中心到外圈均匀。'),
      step(3, 85, 135, 245, '收尾', '注水到 245g，轻晃一次。'),
    ],
    suitableFor: ['水洗', '浅烘', '埃塞俄比亚', '肯尼亚', '花香', '柑橘'],
    avoidFor: ['深烘', '发酵感'],
    flavorGoal: '明亮酸质、花香、干净尾韵。',
    adjustmentRules: [
      '酸尖但甜感不足时研磨略细而不是继续升温。',
      '涩感明显时降低水温 1°C。',
    ],
    sourceNotes: '针对水洗浅烘豆的明亮表达模板。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'natural-berry-sweet',
    name: '日晒莓果甜感模板',
    category: 'bean-specific',
    difficulty: 'easy',
    brewer: 'Kalita Wave 平底滤杯',
    filter: '平底滤纸',
    doseGrams: 16,
    waterGrams: 250,
    ratio: '1:15.6',
    waterTemperatureC: { min: 90, max: 92 },
    grindSize: '中等',
    targetTimeSeconds: { min: 165, max: 205 },
    pourSteps: [
      step(1, 0, 35, 50, '闷蒸', '注水到 50g，减少搅动。'),
      step(2, 35, 75, 125, '甜感段', '低水流注水到 125g。'),
      step(3, 75, 120, 200, '厚度段', '注水到 200g，维持平底水位。'),
      step(4, 120, 155, 250, '收尾', '注水到 250g。'),
    ],
    suitableFor: ['日晒', '莓果', '甜感', '热带水果', '中浅烘'],
    avoidFor: ['极干净水洗'],
    flavorGoal: '圆润甜感和成熟水果调性。',
    adjustmentRules: [
      '发酵味过冲时降低水温。',
      '果汁感不足时略细研磨。',
    ],
    sourceNotes: '针对日晒甜感豆的低扰动模板。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'anaerobic-lower-temp',
    name: '厌氧发酵降温模板',
    category: 'bean-specific',
    difficulty: 'medium',
    brewer: 'Origami',
    filter: '平底滤纸',
    doseGrams: 15,
    waterGrams: 225,
    ratio: '1:15',
    waterTemperatureC: { min: 86, max: 90 },
    grindSize: '中等',
    targetTimeSeconds: { min: 140, max: 180 },
    pourSteps: [
      step(1, 0, 30, 45, '闷蒸', '注水到 45g，轻柔湿润粉层。'),
      step(2, 30, 75, 135, '低扰动主段', '细水流注水到 135g。'),
      step(3, 75, 115, 225, '收尾', '注水到 225g，避免强烈绕圈。'),
    ],
    suitableFor: ['厌氧', '共发酵', '酒香', '发酵感', '热带水果'],
    avoidFor: ['水洗高酸且需要高温萃取'],
    flavorGoal: '控制发酵刺激，保留甜感。',
    adjustmentRules: [
      '酒感刺鼻时继续降温或减少总水量。',
      '风味闷时研磨略粗并缩短时间。',
    ],
    sourceNotes: '针对发酵感强的豆子，降低水温和扰动。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'gesha-floral-high-acid',
    name: '瑰夏花香模板',
    category: 'bean-specific',
    difficulty: 'medium',
    brewer: 'Origami',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 240,
    ratio: '1:16',
    waterTemperatureC: { min: 92, max: 94 },
    grindSize: '中细',
    targetTimeSeconds: { min: 130, max: 165 },
    pourSteps: [
      step(1, 0, 40, 45, '轻柔闷蒸', '注水到 45g，避免过度搅拌。'),
      step(2, 40, 80, 145, '香气段', '中心小圈注水到 145g。'),
      step(3, 80, 120, 240, '清晰收尾', '注水到 240g，保持快流速。'),
    ],
    suitableFor: ['瑰夏', '花香', '茶感', '柑橘', '浅烘'],
    avoidFor: ['深烘', '强发酵'],
    flavorGoal: '花香、茶感、精致酸质。',
    adjustmentRules: [
      '香气被压住时减少晃动。',
      '酸质过尖时降温 1°C。',
    ],
    sourceNotes: '针对瑰夏和高香气豆的低扰动清晰模板。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'dark-roast-low-temp',
    name: '深烘低温低苦模板',
    category: 'bean-specific',
    difficulty: 'easy',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 220,
    ratio: '1:14.7',
    waterTemperatureC: { min: 84, max: 88 },
    grindSize: '中粗',
    targetTimeSeconds: { min: 115, max: 150 },
    pourSteps: [
      step(1, 0, 25, 40, '短闷蒸', '注水到 40g，闷蒸时间不要过长。'),
      step(2, 25, 65, 130, '主注水', '注水到 130g，水流稳定。'),
      step(3, 65, 105, 220, '快速收尾', '注水到 220g，缩短尾段接触。'),
    ],
    suitableFor: ['深烘', '中深烘', '坚果', '巧克力', '低酸'],
    avoidFor: ['浅烘高密度'],
    flavorGoal: '降低苦味和焦感，保留甜感厚度。',
    adjustmentRules: [
      '苦味重时继续降温或研磨更粗。',
      '味道薄时提高粉量或改为 1:14。',
    ],
    sourceNotes: '针对深烘豆降低萃取强度的日常模板。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'new-bean-default',
    name: '新豆试冲默认模板',
    category: 'bean-specific',
    difficulty: 'easy',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 15,
    waterGrams: 240,
    ratio: '1:16',
    waterTemperatureC: { min: 90, max: 93 },
    grindSize: '中细',
    targetTimeSeconds: { min: 140, max: 180 },
    pourSteps: [
      step(1, 0, 35, 45, '闷蒸', '注水到 45g，观察排气状态。'),
      step(2, 35, 85, 150, '主段', '注水到 150g，记录流速和香气。'),
      step(3, 85, 130, 240, '收尾', '注水到 240g，等待完成。'),
    ],
    suitableFor: ['资料不足', '第一次冲煮', '日常', '试冲'],
    avoidFor: [],
    flavorGoal: '用保守参数建立第一次记录，方便下次调整。',
    adjustmentRules: [
      '太酸就提高萃取：细一点、热一点或久一点。',
      '太苦就降低萃取：粗一点、低温一点或短一点。',
    ],
    sourceNotes: '资料不足时的安全默认模板。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'cold-brew-pitcher-classic',
    name: '冷萃壶经典浸泡',
    category: 'cold-brew',
    difficulty: 'easy',
    brewer: '冷萃壶',
    filter: '内置滤网或滤袋',
    doseGrams: 50,
    waterGrams: 600,
    ratio: '1:12',
    waterTemperatureC: { min: 4, max: 8 },
    grindSize: '中粗',
    targetTimeSeconds: { min: 36000, max: 50400 },
    pourSteps: [
      step(1, 0, 120, 0, '加粉', '把咖啡粉放入冷萃壶滤网或滤袋，轻轻摇平。'),
      step(2, 120, 300, 600, '加水', '分两到三次加入冷水到 600g，确保粉层全部湿润。'),
      step(3, 300, 43200, 600, '冷藏浸泡', '放入冰箱冷藏 10-14 小时，中途可轻轻摇晃一次。'),
      step(4, 43200, null, 600, '过滤保存', '取出滤网或滤袋，过滤后冷藏保存，建议 2 天内喝完。'),
    ],
    suitableFor: ['冷萃', '日常', '甜感', '低苦', '中烘', '中浅烘'],
    avoidFor: ['需要热冲香气', '极浅烘高酸豆'],
    flavorGoal: '稳定、低苦、甜感清楚，适合作为冷萃默认方案。',
    adjustmentRules: [
      '酸感尖锐时延长浸泡 2 小时或研磨略细。',
      '苦味重时缩短浸泡或把粉水比放宽到 1:13。',
    ],
    sourceNotes: '冷萃壶通用浸泡模板，优先保证低苦和稳定复现。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'cold-brew-pitcher-bright-clean',
    name: '冷萃壶清爽低苦',
    category: 'cold-brew',
    difficulty: 'easy',
    brewer: '冷萃壶',
    filter: '内置滤网或滤袋',
    doseGrams: 40,
    waterGrams: 520,
    ratio: '1:13',
    waterTemperatureC: { min: 4, max: 8 },
    grindSize: '中粗',
    targetTimeSeconds: { min: 28800, max: 36000 },
    pourSteps: [
      step(1, 0, 120, 0, '加粉', '使用中粗研磨，放入滤网后轻轻铺平。'),
      step(2, 120, 240, 520, '加水', '加入冷水到 520g，避免大力搅拌。'),
      step(3, 240, 32400, 520, '冷藏浸泡', '冷藏 8-10 小时，减少苦味和发酵感被放大。'),
      step(4, 32400, null, 520, '过滤饮用', '过滤后可直接加冰饮用，想更清爽可加少量冰水。'),
    ],
    suitableFor: ['冷萃', '水洗', '浅烘', '花香', '柑橘', '清爽', '低苦'],
    avoidFor: ['深烘', '想要高浓度加奶'],
    flavorGoal: '清爽、低苦、保留花果香，不追求厚重浓度。',
    adjustmentRules: [
      '香气弱时浸泡延长 1-2 小时。',
      '酸感太突出时改用经典浸泡模板或提高粉量。',
    ],
    sourceNotes: '适合水洗和浅烘豆的清爽型冷萃模板。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'cold-brew-pitcher-concentrate',
    name: '冷萃壶浓缩基底',
    category: 'cold-brew',
    difficulty: 'medium',
    brewer: '冷萃壶',
    filter: '内置滤网或滤袋',
    doseGrams: 80,
    waterGrams: 600,
    ratio: '1:7.5',
    waterTemperatureC: { min: 4, max: 8 },
    grindSize: '中粗到粗',
    targetTimeSeconds: { min: 50400, max: 64800 },
    pourSteps: [
      step(1, 0, 120, 0, '加粉', '粉量较高，装粉后轻轻摇匀，避免结块。'),
      step(2, 120, 360, 600, '分次加水', '分三次加入冷水到 600g，每次等待粉层吸水后再补水。'),
      step(3, 360, 57600, 600, '冷藏浸泡', '冷藏 14-18 小时，建立足够浓度。'),
      step(4, 57600, null, 600, '过滤稀释', '过滤后作为基底，可按 1:1 加水、冰块或牛奶稀释。'),
    ],
    suitableFor: ['冷萃', '浓缩基底', '加奶', '巧克力', '坚果', '中深烘', '深烘'],
    avoidFor: ['只想直接喝清爽冷萃', '花香型浅烘豆'],
    flavorGoal: '获得更高浓度，方便加冰、加水或加奶。',
    adjustmentRules: [
      '苦味重时把浸泡缩短到 14 小时。',
      '加奶后味道仍淡时下次提高粉量或延长浸泡。',
    ],
    sourceNotes: '冷萃壶浓缩基底模板，适合做冰咖啡和奶咖啡底。',
    sourceUrls: [],
    isChampionReference: false,
  },
  {
    id: 'champion-2016-kasuya-46',
    name: '冠军参考 2016 Kasuya 4:6',
    category: 'champion-reference',
    difficulty: 'advanced',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 20,
    waterGrams: 300,
    ratio: '1:15',
    waterTemperatureC: { min: 92, max: 92 },
    grindSize: '中粗',
    targetTimeSeconds: { min: 210, max: 240 },
    pourSteps: [
      step(1, 0, 45, 60, '4:6 第一段', '注水到 60g。'),
      step(2, 45, 90, 120, '4:6 第二段', '注水到 120g。'),
      step(3, 90, 135, 180, '浓度段 1', '注水到 180g。'),
      step(4, 135, 180, 240, '浓度段 2', '注水到 240g。'),
      step(5, 180, 225, 300, '浓度段 3', '注水到 300g。'),
    ],
    suitableFor: ['进阶参考', '甜感', '层次', '日晒'],
    avoidFor: ['日常快速冲煮'],
    flavorGoal: '通过前后水量控制酸甜和浓度。',
    adjustmentRules: [
      '此模板受比赛方法启发，应根据实际豆子重新校准。',
      '不确定时优先使用日常 4:6 模板。',
    ],
    sourceNotes: 'World Brewers Cup 2016 Tetsu Kasuya 4:6 方法参考。',
    sourceUrls: ['https://en.wikipedia.org/wiki/World_Brewers_Cup'],
    isChampionReference: true,
  },
  {
    id: 'champion-2021-winton-five-pour',
    name: '冠军参考 2021 Matt Winton 五段',
    category: 'champion-reference',
    difficulty: 'advanced',
    brewer: 'V60',
    filter: '锥形滤纸',
    doseGrams: 20,
    waterGrams: 300,
    ratio: '1:15',
    waterTemperatureC: { min: 88, max: 93 },
    grindSize: '中等',
    targetTimeSeconds: { min: 155, max: 170 },
    pourSteps: [
      step(1, 0, 30, 60, '第一段', '使用较高温水注水到 60g。'),
      step(2, 30, 60, 120, '第二段', '注水到 120g。'),
      step(3, 60, 90, 180, '第三段', '注水到 180g。'),
      step(4, 90, 120, 240, '第四段', '注水到 240g。'),
      step(5, 120, 150, 300, '第五段', '以较低温水收尾到 300g。'),
    ],
    suitableFor: ['进阶参考', '拼配', '复杂层次'],
    avoidFor: ['无温控壶'],
    flavorGoal: '通过多段和温度变化呈现复杂度。',
    adjustmentRules: ['没有双温水条件时不要强行套用。', '可简化为五段同温注水做参考。'],
    sourceNotes: 'World Brewers Cup 2021 Matt Winton 五段注水参考。',
    sourceUrls: ['https://en.wikipedia.org/wiki/World_Brewers_Cup'],
    isChampionReference: true,
  },
  {
    id: 'champion-2023-medina-50g',
    name: '冠军参考 2023 Carlos Medina 五次 50g',
    category: 'champion-reference',
    difficulty: 'advanced',
    brewer: 'Origami',
    filter: '锥形或平底滤纸',
    doseGrams: 15.5,
    waterGrams: 250,
    ratio: '1:16.1',
    waterTemperatureC: { min: 91, max: 91 },
    grindSize: '中等',
    targetTimeSeconds: { min: 145, max: 170 },
    pourSteps: [
      step(1, 0, 30, 50, '第一段', '注水到 50g。'),
      step(2, 30, 60, 100, '第二段', '注水到 100g。'),
      step(3, 60, 90, 150, '第三段', '注水到 150g。'),
      step(4, 90, 120, 200, '第四段', '注水到 200g。'),
      step(5, 120, 150, 250, '第五段', '注水到 250g。'),
    ],
    suitableFor: ['进阶参考', '日晒', '高甜感', 'Origami'],
    avoidFor: ['容易堵塞的豆子'],
    flavorGoal: '五次等量注水，突出甜感和层次。',
    adjustmentRules: ['堵塞时研磨调粗。', '日常使用时可改为 15g:240g。'],
    sourceNotes: 'World Brewers Cup 2023 Carlos Medina 方案参考。',
    sourceUrls: ['https://en.wikipedia.org/wiki/World_Brewers_Cup'],
    isChampionReference: true,
  },
  {
    id: 'champion-2024-wolfl-270g',
    name: '冠军参考 2024 Martin Wolfl 60/60/50/100',
    category: 'champion-reference',
    difficulty: 'advanced',
    brewer: 'Orea',
    filter: 'Sibarist 或快流速平底滤纸',
    doseGrams: 17,
    waterGrams: 270,
    ratio: '1:15.9',
    waterTemperatureC: { min: 93, max: 93 },
    grindSize: '约 630 微米',
    targetTimeSeconds: { min: 150, max: 190 },
    pourSteps: [
      step(1, 0, 40, 60, '闷蒸', '注水到 60g。'),
      step(2, 40, 80, 120, '第二段', '40 秒注水到 120g。'),
      step(3, 80, 120, 170, '第三段', '1:20 注水到 170g。'),
      step(4, 120, 170, 270, '第四段', '2:00 附近注水到 270g。'),
    ],
    suitableFor: ['进阶参考', '瑰夏', '厌氧日晒', '快流速平底'],
    avoidFor: ['普通滤纸流速较慢时'],
    flavorGoal: '在快流速器具中呈现高香气和清晰甜感。',
    adjustmentRules: ['没有相似器具时优先改用 Orea 快流速模板。', '流速慢时研磨需要明显调粗。'],
    sourceNotes: 'World Brewers Cup 2024 Martin Wolfl 方案参考。',
    sourceUrls: ['https://en.wikipedia.org/wiki/World_Brewers_Cup'],
    isChampionReference: true,
  },
  {
    id: 'champion-2025-peng-30-90-90',
    name: '冠军参考 2025 Peng Jinyang 30/90/90',
    category: 'champion-reference',
    difficulty: 'advanced',
    brewer: 'SOLO Dripper',
    filter: '专用滤纸',
    doseGrams: 15,
    waterGrams: 210,
    ratio: '1:14',
    waterTemperatureC: { min: 80, max: 96 },
    grindSize: '中等',
    targetTimeSeconds: { min: 110, max: 150 },
    pourSteps: [
      step(1, 0, 30, 30, '高温第一段', '96°C 注水到 30g。'),
      step(2, 30, 70, 120, '高温第二段', '96°C 注水到 120g。'),
      step(3, 70, 120, 210, '低温收尾', '80°C 注水到 210g，可配合分散注水工具。'),
    ],
    suitableFor: ['进阶参考', '瑰夏', '高香气', '双温水'],
    avoidFor: ['无温控条件', '日常快速记录'],
    flavorGoal: '用双温水控制前段香气和后段萃取强度。',
    adjustmentRules: ['没有双温水时不要强行套用。', '可作为低水量高浓度参考。'],
    sourceNotes: 'World Brewers Cup 2025 Peng Jinyang 30-90-90 技法参考。',
    sourceUrls: ['https://en.wikipedia.org/wiki/World_Brewers_Cup'],
    isChampionReference: true,
  },
]
